VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Tabelle8"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Private Sub CommandButton1_Click()
Call version
End Sub
Private Sub CommandButton2_Click()
Call Dokumenteigenschaften_Ist
End Sub
Private Sub CommandButton3_Click()
Call Dokumenteigenschaften_Soll
End Sub
